"""Add voter_emails to elections

Revision ID: efaba1f5bec0
Revises: 001
Create Date: 2026-01-12 08:05:45.100511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efaba1f5bec0'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('voter_emails', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elections', 'voter_emails')
    # ### end Alembic commands ###
